### ISSUE TITLE
Update python libraries

### ISSUE THREAD

**Issue by raspersc2** [aiarena/aiarena-docker#84]
Dependabot has already put PR in for various libraries that are starting to get a bit out of date, just a request to update these before next ladder season starts.

The main one I was looking at was scipy where the latest version is now 1.8.0 (1.6.3 currently installed) and starting to get deprecation warnings locally / missing out on a lot of optimizations.

https://github.com/scipy/scipy/releases/tag/v1.8.0

**Comment by lladdy** [comment]
Happy to do this.
@Cryptyc does this work for you if we do this after the season end?

**Comment by Cryptyc** [comment]
Yeh, we can do that.  After the season, we should probably see if theres anything else that needs an update.  Season will likely end early June, as thats after a festival I'm running

**Comment by raspersc2** [comment]
Might also be worth a look through libraries dependabot hasn't picked up such as pytorch and openai gym which are several releases behind

Any thoughts on Stable Baselines3 https://github.com/DLR-RM/stable-baselines3 ?

It was used in the latest sentdex tutorial so might be useful in preparation for any new authors

**Comment by lladdy** [comment]
Done - closing.
